"""
This module implements parallelization utils
"""

# This file is part of the simulator_awgn_python distribution
# https://github.com/and-kirill/simulator_awgn_python/.
# Copyright (c) 2023 Kirill Andreev.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

import multiprocessing
import sys
import signal
import logging
from contextlib import contextmanager
from numpy.random import SeedSequence, default_rng

from .tools import dataclass_merge

# A global random state to be used in different processes of the multiprocessing pool
__RNG_INSTANCE = None
# Global per-process experiment instance created by pool init function
__EXP_INSTANCE = None


LOGGER = logging.getLogger(__name__)


def main_loop(experiment_type, experiment_settings, n_workers, mainloop_fcn):
    """
    Wrapper for main-loop simulation function
    """
    # Instantiate experiment before making fork.
    # This will leverage copy-on-write memory management
    global __EXP_INSTANCE
    __EXP_INSTANCE = experiment_type(experiment_settings)
    with init_pool(n_workers) as pool:
        mainloop_fcn(pool)


def schedule_batch(snr_db, batch_size, chunk_size, pool):
    """
    Run single batch for given SNR value. Return multiprocessing async result
    """
    return pool.map_async(
        single_run,
        [(snr_db, chunk_size)] * batch_size
    )


@contextmanager
def init_pool(n_workers):
    """
    Initialize the parallel pool
    """
    LOGGER.info('Initializing pool of %d workers.', n_workers)
    # Use 'fork' to leverage copy-on-write memory management
    ctx = multiprocessing.get_context('fork')
    # Initialize the seed sequence for child processes:
    rng_queue = ctx.Queue()
    for rng in SeedSequence().spawn(n_workers):
        rng_queue.put(rng)
    pool = ctx.Pool(
        processes=n_workers,
        initializer=init_worker,
        initargs=(rng_queue,)
    )

    try:
        yield pool
    finally:
        LOGGER.critical('Closing the pool. If stuck after Ctrl+C, press Ctrl+C again.')
        pool.terminate()
        pool.join()
        LOGGER.info('Pool closed.')


# Below are worker-related methods (All methods are static to avoid serialization)
def single_run(args):
    """
    This is a single test wrapper
    In the case of crash, stacktrace will be written to file
    :param args: required arguments tuple
    """
    snr_db, chunk_size = args
    # Use per-process global random state and experiment instance here (see init_pool)
    entry = __EXP_INSTANCE.run(snr_db, __RNG_INSTANCE)
    if chunk_size > 1:
        data = [__EXP_INSTANCE.run(snr_db, __RNG_INSTANCE) for _ in range(chunk_size - 1)]
        entry = dataclass_merge(entry, data)
    return entry


def sighandler(_, __):
    """
    Signal handler for worker
    In the case of KeyboardInterrupt, hide a large stacktrace generated by workers.
    Just silently exit
    """
    sys.exit(1)


def init_worker(rng_queue):
    """
    Initialize pool worker
    :param rng_queue: Multiprocessing queue with seed list
    :param experiment_type: Experiment class type
    :param experiment_settings: Experiment config instance
    :return: None, just updates all global per-process variables
    """
    signal.signal(signal.SIGINT, sighandler)

    # Initialize random number generator instance:
    global __RNG_INSTANCE
    try:
        __RNG_INSTANCE = default_rng(rng_queue.get())
        rng_queue.close()
    except OSError:
        # If some worker pool_crashed, multiprocessing.Pool() will try to re-initialize a worker
        # This re-created worker will not be able to get a proper seed value
        # Silently exit in this case
        sys.exit(1)
